name: Workflow using GitHub Action

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: SonarQube Scan
      run: |
        sonar-scanner \
          -Dsonar.projectKey=Django_Ecommerce \
          -Dsonar.sources=. \
          -Dsonar.host.url=${{secrets.SONAR_HOST_URL}}
          -Dsonar.login=${{secrets.SONAR_TOKEN}}

    - name: Check Container
      run: docker ps


